name = "shosta-lab"
main = "src/index.js"
compatibility_date = "2026-10-02"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "shosta_lab"
database_id = "2b53500d-a29f-485a-bd23-12368151caff"
migrations_dir = "migrations"
